### ISSUE TITLE
is it okay to write auto playing script?

### ISSUE THREAD

**Issue by huzdor** [moxcomic/archer#12]
![chrome_TX6tBfQ10w](https://github.com/moxcomic/archer/assets/127702159/3e27c61f-46cf-4253-8ee0-7e167b9eff61)

'不可使用自动模式' = 'Automatic mode is not available'
probably it seems like built-in auto mode is disabled.

if built-in auto mode was disabled due to some problem, i'm asking a question because it seems better not to write/use auto playing script.

**Comment by moxcomic** [comment]
- Turning on the first switch means it will call the `auto.go` or `auto.js` file.
- Turning on the second switch means using the built-in call mode.
- Turning on the third switch means using the built-in automatic mode.

If you need to write your own code and make the code move the mouse, turn on switch 1. If you are writing your own code but not moving the mouse by yourself, turn on switches 1 and 2. If you choose not to write any code at all, turn on switches 1, 2, and 3.

**Comment by huzdor** [comment]
problem was solved, thanks!
