### ISSUE TITLE
当前账号授权已到期, 将不会进行计算

### ISSUE THREAD

**Issue by MongMikng** [moxcomic/archer#2]
I'm encountering the same error as mentioned above. Is there a way to purchase a license?

**Comment by moxcomic** [comment]
Sorry for not seeing this issue in time, our software is not very suitable for users who don't know computer knowledge and have low game level, so we need to check your game level first, you can join our group https://discord.gg/vHn6pu7t if you need.

**Comment by miyaring** [comment]
I'm having the same problem, can you re-invite the discord room?

**Comment by moxcomic** [comment]
> I'm having the same problem, can you re-invite the discord room?

You can add our discord channel and contact me!

**Comment by scutfrank** [comment]
直接说要钱这么难吗？
our software is not very suitable for users who don't know computer knowledge and have low game level, so we need to check your game level first, you can add my telegram if you need.
还整这个，骗谁呢！
虚伪！恶心！
